name: 'Setup Git with Token'
description: 'Configures Git with an authorization token'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App Private Key'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
    - name: Add custom URL mappings for GitHub
      shell: bash
      run: |
        # Support for two different URL formats for SSH pulling
        git config --global --add url.https://git:${{ steps.app-token.outputs.token }}@github.com/.insteadOf ssh://git@github.com/
        git config --global --add url.https://git:${{ steps.app-token.outputs.token }}@github.com/.insteadOf git@github.com:
